### PR TITLE
Update merra2_thompson from Dom

### PR DESCRIPTION
**Pull request by climbfuji**
@AnningCheng-NOAA please review and merge if ok. Thanks!

### CODE REVIEW

**Comment by AnningCheng-NOAA** [comment]
HI, Dom,

I merged, but the head of my branch of fv3atm  "mraerosol" is still
at  d840d47d98c1.  Am missing something?

**Comment by climbfuji** [comment]
Yes, your branch that you gave me was merra2_thompson for fv3atm

**Comment by AnningCheng-NOAA** [comment]
HI, Dom:

my branch for fv3atm is mraerosol too. merra2_thompson is the old version,
out of date. Could you correct it?

**Comment by AnningCheng-NOAA** [comment]
Dom,

Never mind. I have just found that merra2_thompson of fv3atm is more
up_to_date with your modifications. I have also bring mraerosl of
ufs_weather_model up_to_date and the code has passed compilation and
waiting for the regression test for merra2_thompson in
/scratch1/NCEPDEV/global/Anning.Cheng/ufs-weather-model/tests/tests.

The other change is that I treat  merra2_aerosol_aware as  parallel to
is_aerosol aware in mp_thompson.F90. I do not understand why you move
merra2_aerosol_aware to the beginning of the code before any
initialization.

Anning

**Comment by climbfuji** [comment]
Thanks for letting me know, I was about to start working on the mraerosol branch.

Which lines of code are you talking about when you refer to "why you move merra2_aerosol_aware to the beginning of the code before any initialization" ?

**Comment by AnningCheng-NOAA** [comment]
Dom,
it is line 157-159 in mp_thompson.F90.  I have moved them to line 217-218
at /scratch1/NCEPDEV/global/Anning.Cheng/ufs-weather-model/FV3/ccpp/physics/physics/mp_thompson.F90.

The regression test has an error at line 174 of mp_thompson.F90. Something
is wrong with passing nwfa. The regression test dir
is /scratch1/NCEPDEV/stmp2/Anning.Cheng/FV3_RT/rt_237272/merra2_thompson

Where are the cap files now? it seems that the compilation automatically
deletes the cap files.

**Comment by climbfuji** [comment]
Your logic is incorrect, because nwfa and nifa will not be converted from moist to dry mixing rattios. That's why I moved the logic up to before the "if(convert_dry_rho)" block.

And is_aerosol_aware and merra2_aerosol_aware should be mutually exclusive, only one of them can be true at any given time. That's how you wrote the code inside module_mp_thompson.F90 and that's what makes sense.

**Comment by AnningCheng-NOAA** [comment]
Dom:

I do not think My logic has any problem. My code is really exclusive for
merra2_aerosol_aware and is_aerosol_aware as below:
if (is_aerosol_aware) then
...
else if (merra2_aerosol_aware) then
...
else
...
end if

Your changes:
if (merra2_aerosol_aware) then
...
end if
if (is_aerosol_aware) then
...
else
...
end if

If both merra_aerosol_aware and is_aerosol_aware are true, my code will be
called only once, your code will be called twice and what has been done in
merra2_aerosol_aware block will be  overwritten by is_aerosol_aware block.

Anyhow, Do you have any idea on how to fix my regression tests?

Anning

**Comment by climbfuji** [comment]
Your logic has a problem because you are not converting from moist to dry mixing ratios/number concentrations (but you are converting back from dry to moist). I agree that your code doesn't have a problem with is_aerosol_aware vs merra2_aerosol_aware.

And if you look carefully in lines 127-131 in mp_thompson.F90, then you will see that my logic is just as fine, too, because is_aerosol_aware and merra2_aerosol_aware cannot be true at the same time.

**Comment by climbfuji** [comment]
I unfortunately won't have time to look into your test before my leave starts. I will be back Oct 18, hopefully you can figure out what the problem is.

**Comment by AnningCheng-NOAA** [comment]
Dom,
I kind of understand, but nifa and nwfa from merra2 climatology are always
dry.  I do not think the necessity to perform such conversion and simply
neglect it.

**Comment by AnningCheng-NOAA** [comment]
Dom, have a nice vacation,

**Comment by climbfuji** [comment]
Thanks! Please make sure to skip the conversion back from dry to moist as well, if merra2 is already dry.

**Pull request merged**
